config/routes.rb
Rails.application.routes.draw do


  root to: "homes#top"
  get "home/about" => "homes#about"
  devise_for :users

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get "daily_posts" => "users#daily_posts"
  end
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  get "search" => "searches#search"
  get "search_tag" => "books#search_tag"

  resources :chats, only: [:create, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :room_users
  has_many :chats


  # フォロワー機能
  # ーーーーーーーーーーーーーーーーーーーー
    #自分がフォローされる関係
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
    # 自分がフォローされている人
  has_many :followers, through: :reverse_of_relationships, source: :follower

    #自分がフォローする関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
    #自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed
  # ーーーーーーーーーーーーーーーーーーーー

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  # フォロワー機能メソッド
  # ーーーーーーーーーーーーーーーーーーーー
  # フォローした時の処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  # ーーーーーーーーーーーーーーーーーーーー

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backword_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io:File.open(file_path), filename: 'default-image.jpg' )
    end
      profile_image.variant(resize_to_limit: [100, 100]).processed
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @post_today = @books.created_today
    @post_yesterday = @books.created_yesterday
    @post_this_week = @books.created_this_week
    @post_last_week = @books.created_last_week
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def daily_posts
    user = User.find(params[:user_id])
    @books = user.books.where(created_at: params[:created_at].to_date.all_day)
    render :daily_posts_form
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_daily_posts_form.html.erb
<div class="my-3">
  <%= form_with url: user_daily_posts_path(user), method: :get, class: "row justify-content-center", local: false do |f| %>
    <div class="col-auto">
      <%= f.date_field :created_at, class: "form-control" %>
    </div>
    <div class="col-auto">
      <%= f.submit "検索" , class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

<div class="daily_posts_table">
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <% if current_user.following?(user) %>
            <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user.id) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%=link_to user.followers.count, user_followers_path(user.id) %></th>
  </tr>
</table>

<div class='row'>
  <% if user == current_user %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% elsif current_user.following?(user) %>
    <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-success" %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-info" %>
  <% end %>

  <% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
    <%= link_to "チャットを始める", chat_path(user.id) %>
  <% end %>
</div>

app/views/users/_record.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">今日の投稿数</th>
      <th scope="col">前日の投稿数</th>
      <th scope="col">前日比</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= post_today.count%></td>
      <td><%= post_yesterday.count %></td>
      <td>
        <% if post_yesterday.count == 0 %>
          前日の投稿はありません
        <% else %>
          <%= (((post_today.count / post_yesterday.count).to_f) * 100).round %>%
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">今週の投稿数</th>
      <th scope="col">前週の投稿数</th>
      <th scope="col">前週比</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= post_this_week.count%></td>
      <td><%= post_last_week.count %></td>
      <td>
        <% if post_last_week.count == 0 %>
          前週の投稿はありません
        <% else %>
          <%= (((post_this_week.count / post_last_week.count).to_f) * 100).round %>%
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

app/views/users/_week_graph.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">6日前</th>
      <th scope="col">5日前</th>
      <th scope="col">4日前</th>
      <th scope="col">3日前</th>
      <th scope="col">2日前</th>
      <th scope="col">1日前</th>
      <th scope="col">今日</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= books.created_6days.count %></td>
      <td><%= books.created_5days.count %></td>
      <td><%= books.created_4days.count %></td>
      <td><%= books.created_3days.count %></td>
      <td><%= books.created_2days.count %></td>
      <td><%= post_yesterday.count %></td>
      <td><%= post_today.count%></td>
    </tr>
  </tbody>
</table>

<canvas id="myLineChart"></canvas>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
  $(document).ready(function () {
    const ctx = document.getElementById("myLineChart");
    const myLineChart = new Chart(ctx, {
      type: 'line',
      data: {
        labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
        datasets: [
          {
            label: '投稿した本の数',
            data: [<%= books.created_6days.count %>, <%= books.created_5days.count %>, <%= books.created_4days.count %>, <%= books.created_3days.count %>, <%= books.created_2days.count %>, <%= post_yesterday.count %>, <%= post_today.count %>],
            borderColor: "rgba(0,0,255,1)",
            backgroundColor: "rgba(0,0,0,0)"
          }
        ],
      },
      options: {
        plugins: {
          title: {
              display: true,
              text: '7日間の投稿数の比較'
          }
        }
      }
    });
    });
</script>

app/views/users/daily_posts_form.js.erb
$('.daily_posts_table').html(`
  <h2>検索結果</h2>
  <div class="card" >
    <div class="card-header">投稿数</div>
    <div class="card-body">
      <%= j( @books.count ) %>
    </div>
  </div>
`)

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>

      <%= render 'daily_posts_form', user: @user %>

      <h2>7日分の投稿数</h2>
      <%= render partial: 'week_graph',
                 locals: { books: @books, post_today: @post_today, post_yesterday: @post_yesterday} %>

      <h2>投稿数の前日比・前週比</h2>
        <%= render partial: 'record',
                   locals: { post_today: @post_today, post_yesterday: @post_yesterday,
                             post_this_week: @post_this_week, post_last_week: @post_last_week} %>
      </div>
    </div>
  </div>
</div>