config/routes.rb
Rails.application.routes.draw do


  root to: "homes#top"
  get "home/about" => "homes#about"
  devise_for :users

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get "daily_posts" => "users#daily_posts"
  end
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  get "search" => "searches#search"
  get "search_tag" => "books#search_tag"

  resources :chats, only: [:create, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  is_impressionable

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :book_tags, dependent: :destroy
  has_many :tags, through: :book_tags

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_2days, -> { where(created_at: 2.days.ago.all_day) }
  scope :created_3days, -> { where(created_at: 3.days.ago.all_day) }
  scope :created_4days, -> { where(created_at: 4.days.ago.all_day) }
  scope :created_5days, -> { where(created_at: 5.days.ago.all_day) }
  scope :created_6days, -> { where(created_at: 6.days.ago.all_day) }

  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.beginning_of_day) }

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def save_tags(sent_tags)
    # タグがnilでなければ、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 登録されていたタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから登録されているタグを除いたタグをnewtagとする
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end

    new_tags.each do |new|
      new_book_tag = Tag.find_or_create_by(name: new)
      self.tags << new_book_tag
    end
  end




  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backword_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  impressionist :acrions => [:show]
  before_action :ensure_correct_user, only:[:edit]

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_post = Book.new
    @book_comment = BookComment.new

    impressionist(@book, nil, unique: [:session_hash.to_s])
  end

  def index
    @books = Book.all.order(params[:sort])
    # to = Time.current.end_of_day
    # from = (to - 6.day).beginning_of_day
    # @books = Book.all.sort { |a,b|
    #   b.favorites.where(created_at: from..to).size <=>
    #   a.favorites.where(created_at: from..to).size
    # }
    @book = Book.new

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    tag_list = params[:book][:tag_name].split(',')
    if @book.save
      @book.save_tags(tag_list)
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def search_tag
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @books = @tag.books.all
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :star)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book, local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>

  <div class="form-group">
    <%= f.label "Tag" %>
    <%= f.text_field :tag_name, class: 'form-control book_tag_name' %>
  </div>

  <div class="form-group row" id="star">
    <%= f.label :star,'評価 ', class:'col-md-3 col-form-label' %>
    <%= f.hidden_field :star, id: :review_star %>
  </div>

  <!-- 評価javascript -->
  <script>
  $('#star').empty();
  $('#star').raty({
    size     : 38,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf : '<%= asset_path('star-half.png') %>',
    scoreName: 'book[star]',
    half: true,
  });
  </script>

  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user.id) do %>
            <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td>
          <% book.tags.each do |tag| %>
            <li style="list-style: none;">
              <%= link_to tag.name, search_tag_path(tag_id: tag.id) %>
            </li>
          <% end %>
        </td>
        <td id="favorites_buttons_<%= book.id %>">
          <%= render 'favorites/favorites', book: book %>
        </td>
        <td>コメント数:<%= book.book_comments.count %></td>
        <td id="star-rate<%= book.id %>"></td>
          <script>
            $('#star-rate<%=   book.id %>').empty();
            $('#star-rate<%= book.id%>').raty({
              size      : 38,
              starOff   : '<%= asset_path('star-off.png') %>',
              starOn    : '<%= asset_path('star-on.png') %>',
              starHalf : '<%= asset_path('star-half.png') %>',
              half      : true,
              readOnly: true,
              score: <%= book.star %>,
            });
          </script>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<%= render 'layouts/errors.html.erb', obj:@book %>
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<%= render 'layouts/errors.html.erb', obj:@book %>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= link_to "新着順", books_path(sort: 'created_at DESC') %> | <%= link_to "評価順", books_path(sort: 'star DESC') %> | <%= link_to "いいね順", books_path(sort: 'book.favorites DESC') %>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/search_tag.html.erb
<div class="container">
  <h3>Books search for "test"</h3>
  <%= render 'books/index', books: @books %>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book_post %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td>
            <% @book.tags.each do |tag| %>
              <li style="list-style: none;">
                <%= link_to tag.name, search_tag_path(tag_id: tag.id) %>
              </li>
            <% end %>
          </td>
          <td id="favorites_buttons_<%= @book.id %>">
            <%= render 'favorites/favorites', book: @book %>
          </td>
          <td id="book_comments_counter"><%= render 'book_comments/counter', book: @book %></td>
          <td id="star-rate<%= @book.id%>"></td>
          <script>
            $('#star-rate<%= @book.id %>').empty();
            $('#star-rate<%= @book.id%>').raty({
              size      : 38,
              starOff   : '<%= asset_path('star-off.png') %>',
              starOn    : '<%= asset_path('star-on.png') %>',
              starHalf : '<%= asset_path('star-half.png') %>',
              half      : true,
              readOnly: true,
              score: <%= @book.star %>,
            });
          </script>
          <% if @user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
          <% end %>
          <% if @user == current_user %>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
          <td>
            閲覧数:<%= @book.impressionist_count(:filter=>:session_hash) %>
          </td>
        </tr>
      </table>

      <div id="comments_area">
        <%= render partial: 'book_comments/book_comments', locals: { book: @book, user: @user } %>
      </div>
      <div class="new_comment">
        <%= render partial: 'book_comments/form', locals: { book: @book, book_comment: @book_comment } %>
      </div>
    </div>
  </div>
</div>